# Generated by Django 5.0.7 on 2024-07-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Singers', '0001_initial'),
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Singers.singer')),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.song')),
            ],
            options={
                'unique_together': {('Song', 'Singer')},
            },
        ),
    ]
