# Generated by Django 5.0.7 on 2024-07-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Songs', '0001_initial'),
        ('choreographyids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreographyDetail',
            fields=[
                ('ChoreographyDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('ChoreographyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choreographyids.choreographyid')),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.song')),
            ],
            options={
                'unique_together': {('Song', 'ChoreographyID')},
            },
        ),
    ]
