# Generated by Django 5.0.7 on 2024-07-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Songs', '0001_initial'),
        ('Writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Songs.song')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Writers.writer')),
            ],
            options={
                'unique_together': {('Song', 'Writer')},
            },
        ),
    ]
