# Generated by Django 5.0.7 on 2024-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_song_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='writer',
            name='date_created',
            field=models.DateField(),
        ),
    ]
