# Generated by Django 5.0.7 on 2024-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_singer_date_created_alter_writer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
