# Generated by Django 5.0.7 on 2024-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_singer_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateField(),
        ),
    ]
