# Generated by Django 5.1 on 2024-08-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_album_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': [('views_album', 'Can view album'), ('archive_album', 'Can archive album'), ('manage_album', 'Can manage album')]},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'permissions': [('views_singer', 'Can view singer'), ('archive_singer', 'Can archive singer'), ('manage_singer', 'Can manage singer')]},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': [('views_song', 'Can view song'), ('archive_song', 'Can archive song'), ('manage_song', 'Can manage song')]},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'permissions': [('views_writer', 'Can view writer'), ('archive_writer', 'Can archive writer'), ('manage_writer', 'Can manage writer')]},
        ),
    ]
