# Generated by Django 5.0.7 on 2024-07-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ReleaseDate', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('DateUpdated', models.DateField(auto_now=True)),
            ],
        ),
    ]
