# Generated by Django 5.0.7 on 2024-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_singer_name_alter_writer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
