# Generated by Django 5.0.7 on 2024-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=5500.67, max_digits=10),
        ),
    ]
